### ISSUE TITLE
Doesnt automatically exit.

### ISSUE THREAD

**Issue by chrcoluk** [jmalarcon/netversion#12]
Tested this on bare metal install of windows and also clean install of windows in a VM, in both cases it detects all .NET versions up to 4.8 then sits there until I abort, the longest case just over 6 hours, whilst sitting there I see no i/o or cpu activity from the process.

Seems hitting enter causes it to exit as well, so is it finishing but just not auto exiting?  The bare metal also has newer versions of .NET which dont show, hence me waiting.

Seems by design this is only for older versions of .NET so i guess its just about the exit behaviour.

https://github.com/jmalarcon/DotNetVersions/issues/3#issuecomment-632116804

**Comment by jmalarcon** [comment]
¿Have you read [the README file](https://github.com/jmalarcon/DotNetVersions) at the main page of this repo? This is the first thing you should do...

This program by default stops after finding the last version of .NET so that you can just double click on it to run it without having a lightning-fast command line opened and closed. If you add the `-b`, `/b` or `--b` switch, that it doesn't stop. That switch is there if you want to use it in a batch file.

**Comment by chrcoluk** [comment]
Apologies, guilty of not reading it properly (skimmed over it), makes sense.

**Comment by jmalarcon** [comment]
No problem 😊
