### ISSUE TITLE
Version display

### ISSUE THREAD

**Issue by Rikk** [jmalarcon/netversion#14]
Hello, I know this nice little app for a long time, but it always reminds me to ask this question:
Shouldn't is say "[4.8.1](https://github.com/jmalarcon/DotNetVersions/blob/master/Program.cs#L141)" somewhere? Not sure everyone will know 4.8.09037 is 4.8.1...

![4.8.1](https://github.com/jmalarcon/DotNetVersions/assets/2916485/2f405a65-2374-40ce-983b-0a4ccfcb9dc1)

**Comment by jmalarcon** [comment]
Hi. Yes, you're right. Maybe I could a simple conditional to show after the real version (maybe something like "4.8.09037 (4.8.1)" or something similar). The problem with this is that if you're using the app to create an automatic report about the current version numbers it will break compatibility 🤔

IMHO the problem is Microsoft and their inconsistency when doing this kind of thing. They should have numbered that version internally 4.8.1 too.

I guess the best way to go is to show the real versions as Microsoft indicates them in the registry. But thanks for your kind comment.

**Comment by Rikk** [comment]
Perhaps you could add a simple switch?

**Comment by jmalarcon** [comment]
Yeah, sure it will be easy, but if you need to turn on that switch and therefore know exactly what you're doing, then you already know what the 4.8.09xxx version is. On the other hand, i f Microsoft releases an update that changes that "magic number" an update to the program will be needed. I'd like to keep things simple in this case 😊
