### ISSUE TITLE
Doesn't run on a fresh Windows 10 VM

### ISSUE THREAD

**Issue by ralbury-mwb** [jmalarcon/netversion#15]
I get a prompt to install the 3.5 runtime (which includes 2.0 and 3.0 as well). Not really the fault of the tool, which works very nicely on my development machine and some of my VMs, just one of the reasons .NET is still problematic when trying to get tools to run on **any** version of Windows from 7 SP1 up to 11 without requiring an installer.

**Comment by jmalarcon** [comment]
Hi: sorry, I missed this one.

It's strange, since every Windows 10 version from 2019 onwards includes .NET 4.8 installed by default. Even the first Windows 10 edition included .NET 4.6. Since .NET 4 includes all the previous versions... it should work!

I don't know what the problem could be....

BTW, this is the source of my information: https://learn.microsoft.com/en-us/archive/blogs/astebner/mailbag-what-version-of-the-net-framework-is-included-in-what-version-of-the-os
