### ISSUE TITLE
Throws System.InvalidOperationException when called from msys/gitbash

### ISSUE THREAD

**Issue by embix** [jmalarcon/netversion#16]
FYI: Due to what looks like[^1] https://github.com/dotnet/runtime/issues/49210 you get an exception when running `DotNetVersions.exe` in gitbash on Windows 10.

```
me@machine → ./DotNetVersions.exe
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.09037

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at DotNetVersions.Program.Main(String[] args)
```

While `winpty DotNetVersions.exe` and `DotNetVersions.exe -b` are workarounds, we probably don't even care as we already got the infos we wanted. It's just annoying/confusing for first time users.

 [^1]: DotNetVersions seems to target .NET Framework 2.0, the referenced but however is for netcore/dotnet5+

**Comment by jmalarcon** [comment]
This app is **Windows only**. 

It's created with .NET Framework 2.0 to ensure it works in very old versions of Windows. It only detects .NET Framework versions, not .NET (so, just "classic" .NET versions only).

It's not mean to be executed under Bash (or GitBash) although I'm surprised it even works there. It's designed to be executed under CMD or PowerShell in Windows. 

However, since the error is because it waits at the end for your input to finish, and that's what's causing the exception, you can just add the documented  `-b` switch at the end to make it end immediately, and it will work without a problem:

![image](https://github.com/user-attachments/assets/1ef15aca-6e30-4c8f-9697-a3b2c7f32db5)

HTH
