### ISSUE TITLE
Support for .net core runtime version

### ISSUE THREAD

**Issue by ancgate** [jmalarcon/netversion#3]
Is there a way to include a check for .net core runtime version.

**Comment by jmalarcon** [comment]
Hi:

This is a .NET Platform version only. In .NET Core there's no need for something like this because it's included out of the box. You can simply run:

```bash
 dotnet --info
```

and you get a list of all the .NET Core runtimes installed, like this:

![List of .NET Core installed runtimes](https://user-images.githubusercontent.com/1775322/82568714-830c6180-9b7f-11ea-83c9-a865e8092bb2.png)

The point of having created DotNetVersions was to allow something like that in the "tradicional" .NET version, since it doesn't have anything like this out of the box.

HTH
