### ISSUE TITLE
Providing an .exe file / more details on how to run the project

### ISSUE THREAD

**Issue by tschomacker** [jmalarcon/netversion#7]
Via the microsoft docs I found your project. It looks promising but I wasn't able to run the project. For me it would be helpful to have a directly executable file or a brief instruction on how I could get the project to run 🤓

**Comment by jmalarcon** [comment]
Hi:

Maybe I'm missing something here, but you have an executable in [the `releases` section](https://github.com/jmalarcon/DotNetVersions/releases/) of the repo. 

Just download the ZIP file there, extract to any folder, and run the `DotNetVersions.exe` file **on Windows**. This is a version for the "classic" .NET framework, so it only works and make sense in Windows.

For .NET Core or .NET 5/6 there's no need for this because it's already included in the CLI:

```bash
dotnet --version
```

and it works multi-platform.

HTH
